[package]
name = "sbahn"
version = "0.1.0"
authors = ["Esteban KÃ¼ber <esteban@kuber.com.ar>"]

[dependencies]
bincode = "*"
env_logger = "*"
eventual = "*"
log = "*"
rand = "0.3"
rustc-serialize = "*"
time = "*"
